# Generated by Django 5.2.4 on 2025-08-19 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField()),
                ('news_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_sources',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_scrapping.newssource')),
            ],
            options={
                'db_table': 'authors',
                'unique_together': {('name', 'source')},
            },
        ),
        migrations.CreateModel(
            name='ScrapingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='started', max_length=20)),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_added', models.IntegerField(default=0)),
                ('articles_updated', models.IntegerField(default=0)),
                ('articles_skipped', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('scheduled_run', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_scrapping.newssource')),
            ],
            options={
                'db_table': 'scraping_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('article_url', models.URLField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='news_scrapping.scrapingrun')),
            ],
            options={
                'db_table': 'scraping_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('paragraph_count', models.IntegerField(default=0)),
                ('featured_image_url', models.URLField(blank=True, max_length=500)),
                ('image_caption', models.TextField(blank=True)),
                ('published_time_str', models.CharField(blank=True, max_length=100)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('has_full_content', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_scrapping.author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news_scrapping.category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_scrapping.newssource')),
                ('tags', models.ManyToManyField(blank=True, to='news_scrapping.tag')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['external_id'], name='articles_externa_22b6c3_idx'), models.Index(fields=['url'], name='articles_url_426d50_idx'), models.Index(fields=['scraped_at'], name='articles_scraped_26dd15_idx'), models.Index(fields=['published_time_str'], name='articles_publish_e4c596_idx')],
                'unique_together': {('external_id', 'source')},
            },
        ),
    ]
