# Generated by Django 5.2.4 on 2025-09-22 21:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrapping', '0004_pushtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('daily_digest', 'Daily News Digest'), ('breaking_news', 'Breaking News'), ('category_update', 'Category Update')], max_length=20)),
                ('title_template', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='BreakingNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('failed_deliveries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breaking_news', to='news_scrapping.article')),
                ('target_categories', models.ManyToManyField(blank=True, to='news_scrapping.category')),
                ('target_sources', models.ManyToManyField(blank=True, to='news_scrapping.newssource')),
            ],
            options={
                'verbose_name_plural': 'Breaking News',
                'db_table': 'breaking_news',
            },
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=10)),
                ('scheduled_time', models.TimeField(default=django.utils.timezone.now)),
                ('next_send_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('max_articles', models.IntegerField(default=5)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('include_categories', models.ManyToManyField(blank=True, to='news_scrapping.category')),
                ('include_sources', models.ManyToManyField(blank=True, to='news_scrapping.newssource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_notifications',
                'indexes': [models.Index(fields=['next_send_at', 'is_active'], name='scheduled_n_next_se_e3c95e_idx'), models.Index(fields=['user', 'is_active'], name='scheduled_n_user_id_ee30f4_idx')],
            },
        ),
    ]
