# Generated by Django 5.2.4 on 2026-02-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_scrapping', '0006_usernotification_articlenotificationhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_date', models.DateField(db_index=True, unique=True)),
                ('digest_text', models.TextField(blank=True)),
                ('top_stories', models.JSONField(blank=True, default=list, help_text='[{article_id, title, why_it_matters, importance}, ...]')),
                ('trending_entities', models.JSONField(blank=True, default=list, help_text='[{entity, type, mention_count, sentiment_trend}, ...]')),
                ('sector_sentiment', models.JSONField(blank=True, default=dict, help_text='{governance: -0.2, entertainment: 0.8, economy: 0.1, ...}')),
                ('story_threads', models.JSONField(blank=True, default=list, help_text='Ongoing multi-day stories to watch')),
                ('under_radar_story', models.JSONField(blank=True, default=dict, help_text='One article that deserves more attention')),
                ('key_concern', models.TextField(blank=True, help_text='One data point that should concern decision-makers')),
                ('articles_analyzed', models.IntegerField(default=0)),
                ('input_tokens_used', models.IntegerField(default=0)),
                ('output_tokens_used', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=60)),
                ('is_published', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_digests',
                'ordering': ['-digest_date'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='started', max_length=20)),
                ('run_type', models.CharField(choices=[('enrichment', 'Article Enrichment'), ('entity_extraction', 'Entity Extraction'), ('daily_digest', 'Daily Digest'), ('retry', 'Retry Failed')], default='enrichment', max_length=30)),
                ('articles_found', models.IntegerField(default=0)),
                ('articles_processed', models.IntegerField(default=0)),
                ('articles_failed', models.IntegerField(default=0)),
                ('articles_skipped', models.IntegerField(default=0)),
                ('total_input_tokens', models.IntegerField(default=0)),
                ('total_output_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'enrichment_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, help_text='2-3 sentence neutral summary')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], max_length=10)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Float from -1.0 (very negative) to 1.0 (very positive)', null=True)),
                ('importance_score', models.IntegerField(blank=True, help_text='Newsworthiness score 1-10', null=True)),
                ('themes', models.JSONField(blank=True, default=list, help_text="e.g. ['governance', 'entertainment', 'economy']")),
                ('key_facts', models.JSONField(blank=True, default=list, help_text='Bullet-point facts extracted from the article')),
                ('related_themes', models.JSONField(blank=True, default=list, help_text='Broader story threads this article connects to')),
                ('entities_people', models.JSONField(blank=True, default=list, help_text='Named persons mentioned')),
                ('entities_organizations', models.JSONField(blank=True, default=list, help_text='Organizations/companies mentioned')),
                ('entities_locations', models.JSONField(blank=True, default=list, help_text='Places mentioned')),
                ('audience_business', models.FloatField(blank=True, help_text='0.0 to 1.0 relevance for business readers', null=True)),
                ('audience_general', models.FloatField(blank=True, help_text='0.0 to 1.0 relevance for general public', null=True)),
                ('audience_government', models.FloatField(blank=True, help_text='0.0 to 1.0 relevance for government/policy readers', null=True)),
                ('audience_youth', models.FloatField(blank=True, help_text='0.0 to 1.0 relevance for youth readers', null=True)),
                ('follow_up_worthy', models.BooleanField(default=False, help_text='Should this story be tracked for follow-up?')),
                ('controversy_flag', models.BooleanField(default=False, help_text='Does this article contain controversial content?')),
                ('is_breaking_candidate', models.BooleanField(default=False, help_text='AI thinks this warrants a breaking news flag')),
                ('input_tokens_used', models.IntegerField(default=0)),
                ('output_tokens_used', models.IntegerField(default=0)),
                ('model_used', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='news_scrapping.article')),
            ],
            options={
                'db_table': 'article_enrichments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntityMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(db_index=True, max_length=200)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization'), ('location', 'Location')], max_length=20)),
                ('mention_date', models.DateField(db_index=True)),
                ('sentiment_score', models.FloatField(blank=True, help_text='Sentiment in context of this entity within the article', null=True)),
                ('context_snippet', models.TextField(blank=True, help_text='Short excerpt showing how entity was mentioned')),
                ('enrichment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mentions', to='newsintelligence.articleenrichment')),
            ],
            options={
                'db_table': 'entity_mentions',
            },
        ),
        migrations.AddIndex(
            model_name='articleenrichment',
            index=models.Index(fields=['status'], name='article_enr_status_ae112a_idx'),
        ),
        migrations.AddIndex(
            model_name='articleenrichment',
            index=models.Index(fields=['sentiment'], name='article_enr_sentime_983e73_idx'),
        ),
        migrations.AddIndex(
            model_name='articleenrichment',
            index=models.Index(fields=['importance_score'], name='article_enr_importa_53c461_idx'),
        ),
        migrations.AddIndex(
            model_name='articleenrichment',
            index=models.Index(fields=['analyzed_at'], name='article_enr_analyze_a9c8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='articleenrichment',
            index=models.Index(fields=['follow_up_worthy'], name='article_enr_follow__8ab1da_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymention',
            index=models.Index(fields=['entity_name', 'mention_date'], name='entity_ment_entity__8d4a56_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymention',
            index=models.Index(fields=['entity_type', 'mention_date'], name='entity_ment_entity__66008c_idx'),
        ),
    ]
