# Generated by Django 5.2.4 on 2026-07-05 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsintelligence', '0003_entitymention_calendar_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Display name in greeting', max_length=120)),
                ('frequency', models.CharField(choices=[('daily', 'Daily (every morning)'), ('breaking', 'Breaking news only')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Set False on unsubscribe — keeps record for analytics')),
                ('unsubscribe_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('confirmed', models.BooleanField(default=False, help_text='True after the confirmation email is clicked')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('last_digest_date', models.DateField(blank=True, help_text='Date of the last digest successfully delivered', null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'digest_subscribers',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['is_active', 'confirmed'], name='digest_subs_is_acti_4d098d_idx'), models.Index(fields=['last_sent_at'], name='digest_subs_last_se_46c30b_idx')],
            },
        ),
    ]
